version: '3'
services:
  nginx:
    container_name: docker-node
    build: ./conf
    ports:
      - "80:80"
      #- "6379:6379" #redis
      #- "27017:27017" #mongodb
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/mongod.conf:/etc/mongod.conf
      - ./conf/redis.conf:/etc/redis.conf
      - ./data:/data/db
      - ./log:/data/logs
      - ./www:/home
    command: [ "/bin/sh", "-c", "/entry.sh && tail -f /dev/null" ]


